Домашняя работа №1
Denisgyngazov/FocusStartHomeworks pull request #1
Opened 2020-10-19 08:50 UTC by Denisgyngazov

Разработано приложение для учета автомобилей, согласно ТЗ.

2020-10-19 14:28 UTC, korshunigor commented
Принято на проверку

2020-10-19 17:36 UTC, korshunigor commented
Давай поправим уже появившиеся замечания и после этого пойдем дальше.

2020-10-19 18:15 UTC, korshunigor requested changes

2020-10-19 18:15 UTC, korshunigor commented on homework 1/Model.swift
> +	}
Лишний отступ у закрывающей скобки

2020-10-19 18:15 UTC, korshunigor commented on homework 1/Model.swift
> +struct Car{
Между Car и { добавь пробел пожалуйста
UPD: перед скобкой { всегда должен быть отступ в 1 пробел (это же замечание в методах)

2020-10-19 18:15 UTC, korshunigor commented on homework 1/Model.swift
> +	let manufacturer : String
При объявлении переменных/констант формат:
let/var **название:** тип
Лишние пробелы

2020-10-19 18:15 UTC, korshunigor commented on homework 1/Model.swift
> +	init(manufacturer: String, model: String, body: String, yearsOfIssue: Int?, carNumber: String?) {
В одну строку параметры удобно читать когда их 1-2, максимум 3, тут уже не очень комфортно, давай каждый вынесем на отдельно строку:
```
init(manufacturer: String, 
      model: String, 
      body: String, 
      yearsOfIssue: Int?, 
      carNumber: String?) {
```
В продолжение к комментарию выше (в enum Body), давай будем принимать на вход body: Body, а не String, это не ошибка, такой вариант возможен, но пока что давай пойдем немного по иному пути.

2020-10-19 18:15 UTC, korshunigor commented on homework 1/Model.swift
> +	case notCorrect = "Некоректный тип"
"Некорректный тип" звучит как ошибка =)
Давай пока что не будем обрабатывать такой сценарий, а будем просить пользователя ввести одно из тех значений, с которыми мы умеем работать.

2020-10-19 18:15 UTC, korshunigor commented on homework 1/main.swift
> +//
В файле много съехавших отступов, чтобы править не вручную сделай следующее:

1. открой данный файл
2. нажми комбинацию Command + A (выделить все)
3. нажми комбинацию Control + I (исправит отступы в выделенном коде)

2020-10-19 18:15 UTC, korshunigor commented on homework 1/main.swift
> +var cars = Array<Car>()
Между методами должен быть отступ в 1 пустую строку

2020-10-19 18:15 UTC, korshunigor commented on homework 1/main.swift
> +	var manufacturer = readLine()!
Если что-то может пойти не так, то оно пойдет не так, по этому давай сразу привыкать избегать использования  force unwrap.

2020-10-19 18:15 UTC, korshunigor commented on homework 1/main.swift
> +	let addCar = Car(manufacturer: manufacturer, model: model, body: body,yearsOfIssue: Int(yearsOfIssue), carNumber: carNumber)
1) Пропущен пробел body,yearsOfIssue
2) Т.к. тут очень много параметров, давай каждый из них вынесем на отдельную строку

2020-10-19 18:15 UTC, korshunigor commented on homework 1/main.swift
> +	while(manufacturer == ""){
Немного лучше будет, если использовать проверку value.isEmpty()

2020-10-19 18:15 UTC, korshunigor commented on homework 1/main.swift
> +	}
Хорошая практика оформления кода - вынос дублируемого кода в универсальные методы, которые можно переиспользовать. Выделенный блок кода встречается несколько раз, но с разными текстами ошибок, это уже признак того, что мы можем попробовать сделать универсальный метод.

Основные критерии:
1. возможность менять текст ошибки
2. на выходе должны получать не опциональную строку

Попробуй выполнить их, используя данный шаблон метода, а затем использовать его в местах, которые очень схожи с ним
```
func readString(errorMessage: String = "Введено неверное значение, повторите попытку") -> String {
	// код метода
}
```

2020-10-19 18:15 UTC, korshunigor commented on homework 1/main.swift
> +	}
Учитывая то что пользователь не знает, какие типы кузова мы поддерживаем, сейчас в 99% мы будем получать кейс notCorrect. Давай сделаем ввод типа кузова аналогично тому как работает меню, каждому пейсу типу кузова присвоим номер и выведем пользователю доступные варианты.

2020-10-20 16:25 UTC, korshunigor requested changes

2020-10-20 16:25 UTC, korshunigor commented on homework 1/Model.swift
> +
Пустая строка, можно удалить.

2020-10-20 16:25 UTC, korshunigor commented on homework 1/Model.swift
> +	case Купе = "3"
Русский язык ни в коем случае не используем для названия переменных/функций/кейсов + надо использовать camelCase (в случае с кейсами, первая буква должна быть маленькая).

Если нужно представление кейсов на русском языке, то лучше сделать отдельное вычислимое свойство внутри enum

```
enum Body {
    case sedan
    case ....

    var name: String {
        switch self {
            case .sedan: return "Седан"
        }
    }
}
```

2020-10-20 16:25 UTC, korshunigor commented on homework 1/main.swift
> +while(true){
Скобки лишние и нужно добавить пробелы
`while true {`
Посимпатичнее выглядит )

2020-10-20 16:25 UTC, korshunigor commented on homework 1/main.swift
> +		  "\n----------------------")
Представим, что через неделю мы решим поддержать еще один тип кузовов, в итоге, нам надо будет добавить его в наш enum, добавить вот сюда в вывод списка кузовов, а еще обновить обработку ввода данных пользователем, это не круто.

Вместо этого мы можем реализовать протокол `CaseIterable` в нашем `enum Body` + сделать доработку, которую указала в замечании к enum-у, это позволит нам извлечь список всех поддерживаемых кейсов, тогда можно будет избавиться от перечисления всех этих строк, а сделать просто:
```
for body in Body.allCases {
    print("\(body.rawValue) - \(body.name)")
}
```

Вместо вечного перечисления всех кейсов, мы получим меню, которое способно работать хоть с 1, хоть с 30 типами кузовов

2020-10-20 16:25 UTC, korshunigor commented on homework 1/main.swift
> +func filterCar(car: Car,filterId: String) -> Bool {
1) Проблема с пробелом `Car,filterId:`, код сливается
2) filterId очень абстрактно, представим, что это API, в реализацию которого мы не можем заглянуть, тогда глядя на этот параметр мы не сможем понять, а как он отфильтрует, на основе чего
3) Этот метод избыточен, мы можем обойтись без него (об этом подробнее в другом замечании)

2020-10-20 16:25 UTC, korshunigor commented on homework 1/main.swift
> +func readString(errorMesage: String = "Введено неверное значение, повторите попытку") -> String {
Так, подожди, этот метод я предлагал сделать для того чтобы избавиться от часто встречаемого повторяющегося кода чтения строки в цикле (который по сути у нас и остался). Само название метода "readString" говорит о том, что мы должны считать строку с консоли, а т.к. мы возвращаем не опциональную строку подразумевается что мы должны ее гарантированно прочесть (в отличии от стандартного readLine). В текущем виде метод возвращает нам отправленный нами параметр, с тем же успехом мы могли его вообще не писать...

Реализуй пожалуйста в этом методе логику, которая заменит вот этот блок кода:
```
guard var manufacturer = readLine() else { return }
 	while (manufacturer.isEmpty){
 	print(readString())
 	manufacturer = readLine() ?? ""
 }
```

Критерии примемки:
1) передаваемое в метод errorMesage отображается когда пользователь ввел пустую строку/строка не считалась
2) в основном коде программы ее можно использовать как `let manufacturer = readString ()` и гарантированно получить ожидаемую нами строку

2020-10-20 16:25 UTC, korshunigor commented on homework 1/main.swift
> +			}else if (menuBody == "2"){
1) Беда с пробелами `"1"){`, между скобками потерялся
2) Сейчас логика работает так: у меня 30 автомобилей, 29 из них у с корпусом "универсал" и 1 "седан", пользователь выбрал, что хочет вывести только автомобили с типом "седан", из-за чего в консоль будет выведено 29 сообщений "Авто с данным типом кузова отсутвуют" и информация об 1 автомобиле

Что предлагаю сделать: вместо перечислений вроде `if (menuBody == "1")` сразу же сделать определение, а какой кейс выбрал пользователь, то есть сделать `let selectedBody: Body`, далее, вместо цикла `for i` использовать стандартную функцию:
`let filteredCars = cars.filter { $0.body == selectedBody }`
За счет этого избавимся от кучи ифов и необходимости перечислять каждый тип корпуса строкой

2020-10-21 08:37 UTC, korshunigor requested changes

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +	let swithcMenu = readLine()
Очепятка )
swit**hc**Menu

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +	if (swithcMenu == "0"){
1) можно опустить круглые скобки
2) снова потерялся пробел между ){

Вообще, это условие такая же обработка выбора пользователя, как и `case "3"`, и `case "2":`, и т.д., по этому было бы логично сделать это тоже с помощью `case "0"`. Проблема в том, что `break` завершает обработку кейса, а не цикла, но у нас же данный кейс отвечает за корректное завершение программы (т.к. 0 соответствует пункту "Выход"), а значит мы можем воспользоваться командой `exit(0)`, то есть завершить выполнение команды с кодом 0. Ну или воспользоваться return, он тоже завершит выполнение цикла.

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +		if (cars.isEmpty == false) {
Можно опустить круглые скобки

Форма записи `flag == false` это хорошо, мы ей тоже пользуемся, удобнее читать чем `!flag` =)
Можно немного упростить код, используя просто `if cars.isEmpty {` и поменяв очередность обработки местами, это не ошибка, но уберем лишнюю операцию сравнения.

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +	let selectedBody: Body = Body(rawValue: Int(menu)!)!
1) Название переменной `menu` не очень интуитивно, не понятно из контекста для чего она, по этому давай назовем ее как-нибудь вроде `selectedBodyNumberString`, для того чтобы мы понимали, что тут будет номер выбранного корпуса, но в строковом представлении
2) Два форс анврапа при попытке получить тип `Body` не есть хорошо, приложение крашнется, если я введу "е" вместо ожидаемых нами кейса

Вместо использования форс анврапа мы можем извлечь значение безопасным способом, используя все тот же `guard`, просто перечислив нужные нам условия через запятую:
```swift
guard let selectedBodyNumberString = readLine(),
           let selectedBodyNumber = Int(selectedBodyNumberString),
	   let selectedBody = Body(rawValue: selectedBodyNumber) else {
    return
}
```

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +	for i in filteredCars {
i - обще принятое название счетчика, тут же это не индекс, а полноценный элемент, по этому давай назовем его так, чтобы он отражал содержащиеся в нем данные, например `car`

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +func printCar(car:Car) {
1) Потерян пробел между типом и двоеточием`(car:Car`
2) Ошибки как таковой с названием нет, но стилистически, можно сделать немного иначе

Сейчас у нас слово car фигурирует как в названии метода, так и в названии входного параметра, конкретно в данном случае мы можем опустить название входного параметра т.к. из названия метода понятно, что именно он принимает на вход, предлагаю заменить данный метод на `printCar(_ car: Car)`, тогда его вызов будет выглядеть так: `printCar(car)` вместо `printCar(car: car)`

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +					 carNumber: carNumber)
1) Год выпуска автомобиля и гос номер не являются обязательными полями, однако по коду сейчас они обязательны
2) Снова двойной форс анврап на попытке получить тип корпуса Body

Надо бы поправить

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +		  "\nГос номер: ", car.carNumber == nil ? "": car.carNumber! as Any,
1) Лучше подготовку данных вынести за пределы функции print, потому что это будет просто напросто удобнее для чтения и для работы с кодом
2) каст `car.yearsOfIssue! as Any` очень страшная штука, потому что опять же форс анврап (хоть мы и убедились, что поле не пустое), можно обойтись и без них

Нам ни чего не мешает перед print создать две константы, в которые будет развернуты опционалы. Для получения строкового представления числа можно использовать свойство `.description` из самого числа, например `car.yearsOfIssue?.description`.

Цитата из условия ДЗ:
Для необязательных полей при отсутствии значения:
• год выпуска – отображать «-»
• **гос номер – пропускать это поле (оно не должно отображаться)**

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +	while (value.isEmpty){
Круглые скобки лишние + потерялся пробел между круглой и фигурной скобкой

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +		if (cars.isEmpty == false) {
В кейсе 2 аналогично

2020-10-21 08:37 UTC, korshunigor commented on homework 1/main.swift
> +			for i in cars {
i - счетчик, а тут модель с данными, давай переименуем в car

2020-10-21 08:59 UTC, Denisgyngazov commented on homework 1/main.swift
> +	let selectedBody: Body = Body(rawValue: Int(menu)!)!
Гениально)

2020-10-22 02:09 UTC, Denisgyngazov commented on homework 1/main.swift
> +					 carNumber: carNumber)
Не совсем тебя понял, в коде ты можешь ввести это значение а можешь не вводить, соответсвенно туда может приходить nil

2020-10-22 06:31 UTC, korshunigor commented on homework 1/main.swift
> +					 carNumber: carNumber)
Сейчас у нас ставится return если функция readLine вернула nil. Да, поддерживается вариант получения строки "", но не поддерживается nil.

Представим, что мы читаем данные не из консоли, а запрашиваем их из API (допустим тянем данные с сервера), получаем JSON, который нужно распарсить, в таком случае мы просто не получим поле для которого нет значения и наш код, ожидающий "" посчитает что значение некорректное и проигнорирует объект. Опциональным сейчас по сути является только yearsOfIssue и то, пользователь обязан ввести хотя бы "" и только потом мы получим nil при касте, если пользователь ввел не число, а в carNumber всегда будет как минимум "", что не совсем корректно по условию.

2020-10-22 18:09 UTC, korshunigor requested changes

2020-10-22 18:09 UTC, korshunigor commented on homework 1/main.swift
> +	guard let carNumber = readLine() else { return }
Т.к. это не обязательные поля нас вполне устроит вариант с nil.
Можно сделать так:
```swift
print("----------------------")
print("Введите год автомобиля:")
let yearsOfIssue = Int(readLine() ?? "")
print("----------------------")
print("Введите государественный знак автомобиля:")
let carNumber = readLine()
```

2020-10-22 18:09 UTC, korshunigor commented on homework 1/main.swift
> +					 yearsOfIssue: Int((yearsOfIssue)),
Двойные скобки чтобы не сбежала переменная?))
После внесения изменений из коммента выше можно будет убрать этот каст

2020-10-22 18:09 UTC, korshunigor commented on homework 1/main.swift
> +	guard let carNumber = car.carNumber?.description == nil ? "" : car.carNumber?.description else { return }
Можно же упростить (ранее вроде даже писал об этом), как таковой guard нам не нужен ни в одном из случаев.

Мы же можем развернуть опционал установкой значения по умолчанию (вместо тернарного оператора)
```swift
let yearsOfIssue = car.yearsOfIssue?.description ?? "-"
let carNumber = car.carNumber ?? ""
```
По условию задания подразумевалось, что если нет гос номера, то мы впринципе не делаем отображение строки с этим полем (не то что само значение отсутствует, а отсутствует строка с этим полем впринципе)

2020-10-22 18:09 UTC, korshunigor commented on homework 1/main.swift
> +	guard var value = readLine() else { return errorMesage }
1) return errorMesage впринципе не корректен, т.к. тот кто будет вызывать этот метод ожидает сроку введенную пользователем, а не ошибку вернувшуюся вместо значения
2) тут можно не использовать guard, можно же сделать также, как в цикле, поставить значение по умолчанию:
```swift
var value = readLine() ?? ""
```
Так мы сможем избавиться от странного возврата ошибки вместо значения (чего не ожидают те кто может воспользоваться этим методом) и развернем опционал

2020-10-22 18:09 UTC, korshunigor commented on homework 1/main.swift
> +	let selectedBody = Body(rawValue: selectedBodyNumber) else { return }
Когда используют многострочный guard используют немного иное форматирование, как правило что-то такое:
```swift
	guard let selectedBodyNumberString = readLine(),
		  let selectedBodyNumber = Int(selectedBodyNumberString),
		  let selectedBody = Body(rawValue: selectedBodyNumber) else {
		return
	}
```
чтобы guard как-то визуально отделялся и было явно видно где он заканчивается (можно выделить этот блок кода и нажать Command + I, Xcode сам поправит отступы)

Минор )

2020-10-22 18:09 UTC, korshunigor commented on homework 1/main.swift
> +		exit(0)
За завершение программы вроде согласно менюшке отвечает ""\n0 - Выход",", давай сделаем корректный вариант, exit(0) перенесем в case соответствующий выходу, а в default можно сделать либо обычный break, либо какой-нибудь print с информацией о том что введен не верный вариант

2020-10-23 01:23 UTC, Denisgyngazov commented on homework 1/main.swift
> +	guard let carNumber = readLine() else { return }
`let yearsOfIssue = Int(readLine() ?? "")`
xcode говрит, что правая часть выражения не будет использоваться никогда

2020-10-23 09:30 UTC, korshunigor requested changes
Последний косячок )

2020-10-23 09:30 UTC, korshunigor commented on homework 1/main.swift
> +	guard let carNumber = readLine() else { return  }
Но ведь нас вполне устраивает, если тут мы получим nil, это же опциональное поле, пусть будет просто
```swift
let carNumber = readLine()
```

2020-10-23 09:32 UTC, korshunigor commented on homework 1/main.swift
> +	guard let carNumber = readLine() else { return }
Странно, у меня такой ошибки нет

2020-10-23 09:44 UTC, Denisgyngazov commented on homework 1/main.swift
> +	guard let carNumber = readLine() else { return }
Я тебе скину в лс)

2020-10-23 10:17 UTC, korshunigor approved these changes

2020-10-23 11:38 UTC, merged