Feature/homework 2
Denisgyngazov/FocusStartHomeworks pull request #2
Opened 2020-10-26 08:36 UTC by Denisgyngazov

Разработанно приложение, реализующее потокобезопассную коллекцию.

2020-10-26 09:41 UTC, korshunigor commented
Принято на проверку

2020-11-06 16:44 UTC, Jinfaa commented on homework-2/homework-2/ThreadSafeArrayApp.swift
> +	let isolationQueue = DispatchQueue(label: "com.homework-2.isolation", attributes: .concurrent)
уровень доступа

2020-11-06 16:45 UTC, Jinfaa commented on homework-2/homework-2/ThreadSafeArrayApp.swift
> +		isolationQueue.async(flags: .barrier) {
еще про self не забывай

2020-11-06 16:46 UTC, Jinfaa commented on homework-2/homework-2/ThreadSafeArrayApp.swift
> +			self.threadSafeArray.append(item)
weak в блоке упущен

2020-11-06 16:50 UTC, Jinfaa requested changes
Нужно немного доработать

2020-11-14 08:35 UTC, merged