Feature: Разработан первый, второй и третий экран
Denisgyngazov/FocusStartHomeworks pull request #3
Opened 2020-11-03 10:42 UTC by Denisgyngazov

Разработано приложение с тремя экранами в соответсвии ТЗ, каждый экран находится на соответствующей вкладке tabBara.

2020-11-03 10:55 UTC, GkFoxes commented
Принял на проверку, передаю другому преподавателю!

2020-11-13 06:44 UTC, Viscount88 submitted a review, later dismissed
Хорошая работа, существенных замечаний нет

2020-11-15 17:04 UTC, Viscount88 requested changes
Так как задание на UI - обращу внимание на то, что при запуске приложения не видны текст и иконка у табов, кроме первого. Становятся видны только после щелчка по ним. Получается багос, надо фиксить.

2020-11-19 02:17 UTC, Denisgyngazov commented
У меня Полина посмотрела 3, 4, 5 работу и дала апруф

2020-11-24 10:03 UTC, Viscount88 approved these changes
Хорошая работа! Разбиение по классам, методам, код аккуратный и читаемый. Существенных замечаний нет.

2020-11-26 10:29 UTC, merged