Feature: Разработан UISplitViewController
Denisgyngazov/FocusStartHomeworks pull request #4
Opened 2020-11-08 08:21 UTC by Denisgyngazov

Разработано приложение, состоящее из UISplitViewController’a. Где в master показывается UITableView, а в detail, description и  картинки с тенями.

2020-11-08 11:38 UTC, noreasonwhyiamhere commented
Задание принято на проверку)

2020-11-19 07:08 UTC, Denisgyngazov commented
У меня Полина посмотрела 3, 4, 5 работу и дала апруф

2020-11-19 12:04 UTC, noreasonwhyiamhere commented
такс я смотрела в большей степени архитектуру, так что это не отменяет остальной проверки 🙂

2020-11-21 15:53 UTC, Jinfaa commented on homework-4/homework-4/Controller/DetailViewController.swift
> +
пустые строки

2020-11-21 15:54 UTC, Jinfaa commented on homework-4/homework-4/Controller/DetailViewController.swift
> +	private var desctiptionText: String
let

2020-11-21 15:54 UTC, Jinfaa commented on homework-4/homework-4/Controller/MasterTableViewCell.swift
> +	static let identifaer = String(describing: MasterTableViewCell.self)
опечатка

2020-11-21 15:54 UTC, Jinfaa commented on homework-4/homework-4/Controller/MasterTableViewCell.swift
> +			titleLabel.leadingAnchor.constraint(equalTo: contentView.leadingAnchor,
форматирование

2020-11-21 15:55 UTC, Jinfaa commented on homework-4/homework-4/Controller/MasterViewController.swift
> +	let mockData: [Mock] = Mock.mockData()
уровень доступа

2020-11-21 15:56 UTC, Jinfaa commented on homework-4/homework-4/Controller/MasterViewController.swift
> +
пустые строки

2020-11-21 16:06 UTC, Jinfaa commented on homework-4/homework-4/Controller/MasterViewController.swift
> +			let navigationController = UINavigationController(rootViewController: detailViewController)
https://github.com/Denisgyngazov/FocusStartHomeworks/pull/4/files#diff-b1d4e7235de1738be3fb5a25110ce096be5d735a9dc6d243e0625cfd1416a704R22

2020-11-21 16:09 UTC, Jinfaa requested changes
Требуются доработки

2020-11-22 09:48 UTC, Denisgyngazov commented on homework-4/homework-4/Controller/MasterTableViewCell.swift
> +			titleLabel.leadingAnchor.constraint(equalTo: contentView.leadingAnchor,
Не понял, что это значит, если ты про переносы, то они автоматически выставляются через control+i

2020-11-24 07:11 UTC, Jinfaa commented on homework-4/homework-4/Controller/MasterViewController.swift
> +			let navigationController = UINavigationController(rootViewController: detailViewController)
так что касается этого?

2020-11-24 07:11 UTC, Jinfaa reviewed
Уточнение

2020-11-24 08:56 UTC, Denisgyngazov commented on homework-4/homework-4/Controller/MasterViewController.swift
> +			let navigationController = UINavigationController(rootViewController: detailViewController)
А что тут не так?

2020-11-24 08:56 UTC, Denisgyngazov commented on homework-4/homework-4/Controller/MasterViewController.swift
> +			let navigationController = UINavigationController(rootViewController: detailViewController)
data source и delegate вынести?

2020-12-04 10:10 UTC, Jinfaa commented
Можно мержить

2020-12-04 15:03 UTC, merged